export const dimsumProducts = [
  {
    id: 1,
    name: "Sủi Cảo Thịt",
    description: "Vỏ mỏng, nhân thịt tươi ngon, chế biến trong ngày.",
    price: 55000,
    category: "Sủi Cảo",
    img: "https://images.unsplash.com/photo-1496116218417-1a781b1c416c?q=80&w=500",
  },
  {
    id: 2,
    name: "Há Cảo Tôm Hấp",
    description: "Há cảo tôm tươi nguyên con, vỏ trong suốt, dai mềm.",
    price: 60000,
    category: "Há Cảo",
    img: "https://images.unsplash.com/photo-1523905330026-b8bd1f5f320e?q=80&w=500",
  },
  {
    id: 3,
    name: "Xíu Mại Gạch Cua",
    description: "Nhân thịt và tôm thơm ngon, phủ gạch cua xay.",
    price: 50000,
    category: "Xíu Mại",
    img: "https://cdn.tgdd.vn/2022/05/CookDish/xiu-mai-la-gi-nguon-goc-va-cach-lam-xiu-mai-thom-ngon-don-avt-1200x676-1.jpg",
  },
  {
    id: 4,
    name: "Bánh Bao Kim Sa",
    description: "Vỏ bánh mềm mịn, nhân trứng muối tan chảy ngọt ngào.",
    price: 45000,
    category: "Bánh Bao",
    img: "https://product.hstatic.net/200000294188/product/banh-bao-kim-sa_8f46b51884f54c4cb26609536a59110d_384326591e0846d2a55c9d400e4855b3_1024x1024.png",
  },
  {
    id: 5,
    name: "Sủi Cảo Chiên",
    description: "Sủi cảo thịt chiên giòn rụm, ăn kèm nước chấm riêng.",
    price: 58000,
    category: "Sủi Cảo",
    img: "https://down-vn.img.susercontent.com/file/sg-11134201-22100-umm5iz9fizivdc.webp",
  },
  // --- BẮT ĐẦU FAKE THÊM 10 MÓN ---
  {
    id: 6,
    name: "Chân Gà Tàu Xì",
    description: "Chân gà mềm rục, thấm đẫm sốt tàu xì đậm đà đặc trưng.",
    price: 65000,
    category: "Món Hấp",
    img: "https://i.ytimg.com/vi/lJdE8v3UofM/maxresdefault.jpg",
  },
  {
    id: 7,
    name: "Sườn Non Sốt Tàu Xì",
    description: "Sườn non chặt nhỏ hấp cùng tàu xì và ớt khô thơm nồng.",
    price: 68000,
    category: "Món Hấp",
    img: "https://Daynauan.info.vn/wp-content/uploads/2018/04/suon-hap-tau-xi.jpg",
  },
  {
    id: 8,
    name: "Bánh Cuốn Tôm tươi",
    description: "Bánh cuốn (Cheung Fun) nhân tôm, rưới nước tương ngọt.",
    price: 75000,
    category: "Bánh Cuốn",
    img: "https://i.ytimg.com/vi/W_aV_u30qFw/maxresdefault.jpg",
  },
  {
    id: 9,
    name: "Há Cảo Hẹ",
    description: "Nhân tôm thịt kết hợp với hẹ tươi, vị thanh mát.",
    price: 52000,
    category: "Há Cảo",
    img: "https://bizweb.dktcdn.net/100/409/017/products/ha-cao-he.jpg?v=1604983053747",
  },
  {
    id: 10,
    name: "Bánh Bao Xá Xíu",
    description: "Nhân thịt xá xíu đậm đà, vỏ bánh trắng ngần mềm xốp.",
    price: 42000,
    category: "Bánh Bao",
    img: "https://cdn.tgdd.vn/Files/2021/08/17/1375765/cactràh-lam-banh-bao-xa-xiu-mem-ngon-dam-da-chuan-vi-ngoai-hang-202206021319245195.jpg",
  },
  {
    id: 11,
    name: "Xôi Lá Sen",
    description: "Xôi nếp dẻo thơm bọc trong lá sen với nhân thịt gà, nấm.",
    price: 55000,
    category: "Món Hấp",
    img: "https://daotaobeptrang.com/wp-content/uploads/2020/02/cach-lam-xoi-hap-la-sen.jpg",
  },
  {
    id: 12,
    name: "Đậu Hũ Ki Cuộn Tôm Chiên",
    description: "Lớp vỏ đậu hũ ki giòn tan, nhân tôm tươi sần sật.",
    price: 70000,
    category: "Món Chiên",
    img: "https://i.ytimg.com/vi/1n8D_rW-O_I/maxresdefault.jpg",
  },
  {
    id: 13,
    name: "Bánh Cuốn Xá Xíu",
    description: "Bánh cuốn mỏng mịn nhân thịt xá xíu thái lựu.",
    price: 70000,
    category: "Bánh Cuốn",
    img: "https://i.ytimg.com/vi/Yf85p-O7XhI/maxresdefault.jpg",
  },
  {
    id: 14,
    name: "Bánh Tart Trứng",
    description: "Lớp vỏ ngàn lớp giòn rụm, nhân kem trứng nướng béo ngậy.",
    price: 48000,
    category: "Tráng Miệng",
    img: "https://beptruong.edu.vn/wp-content/uploads/2013/11/banh-tart-trung.jpg",
  },
  {
    id: 15,
    name: "Cao Quy Linh",
    description: "Món tráng miệng thanh mát, giải nhiệt cực tốt.",
    price: 35000,
    category: "Tráng Miệng",
    img: "https://down-vn.img.susercontent.com/file/860a5b604fc1d210e7ed6a45f466ba76@resize_w900_nl.webp",
  },
  // --- TIẾP TỤC FAKE THÊM 20 MÓN (ID 16 - 35) ---
  {
    id: 16,
    name: "Há Cảo Thủy Tinh",
    description: "Lớp vỏ trong suốt như pha lê, nhân tôm tươi đỏ hồng đẹp mắt.",
    price: 62000,
    category: "Há Cảo",
    img: "https://nguyenlieunhahang.vn/wp-content/uploads/2021/04/ha-cao-thuy-tinh.jpg",
  },
  {
    id: 17,
    name: "Xíu Mại Trứng Muối",
    description:
      "Sự kết hợp hoàn hảo giữa thịt băm và lòng đỏ trứng muối bùi béo.",
    price: 58000,
    category: "Xíu Mại",
    img: "https://i.ytimg.com/vi/S-U5T8YvQ9Y/maxresdefault.jpg",
  },
  {
    id: 18,
    name: "Bánh Cuốn Xá Xíu",
    description: "Lớp bánh mướt mịn cuộn nhân thịt xá xíu đậm đà.",
    price: 72000,
    category: "Bánh Cuốn",
    img: "https://i.ytimg.com/vi/Yf85p-O7XhI/maxresdefault.jpg",
  },
  {
    id: 19,
    name: "Sườn Hấp Khoai Môn",
    description:
      "Sườn non mềm ngọt hấp cùng khoai môn bùi béo, thơm mùi tàu xì.",
    price: 68000,
    category: "Món Hấp",
    img: "https://daynauan.info.vn/wp-content/uploads/2018/04/suon-hap-tau-xi.jpg",
  },
  {
    id: 20,
    name: "Chả Giò Triều Châu",
    description: "Nhân khoai môn, nấm mèo và thịt, chiên vàng giòn rụm.",
    price: 55000,
    category: "Món Chiên",
    img: "https://i.ytimg.com/vi/8E3hX-j7Z4U/maxresdefault.jpg",
  },
  {
    id: 21,
    name: "Bánh Xếp Thượng Hải (XLB)",
    description: "Tiểu lung bao với nước súp ngọt thanh bên trong lớp vỏ mỏng.",
    price: 85000,
    category: "Món Hấp",
    img: "https://vcdn1-du-lich.vnecdn.net/2021/04/23/Xlb-1619163283-9366-1619163351.jpg",
  },
  {
    id: 22,
    name: "Bánh Khoai Môn Chiên Xù",
    description: "Lớp vỏ tạo hình tổ chim giòn tan, nhân khoai môn thịt băm.",
    price: 52000,
    category: "Món Chiên",
    img: "https://beptruong.edu.vn/wp-content/uploads/2018/06/banh-khoai-mon-chien-xu.jpg",
  },
  {
    id: 23,
    name: "Cháo Trứng Bách Thảo",
    description: "Cháo trắng nấu nhừ với thịt băm và trứng bách thảo bổ dưỡng.",
    price: 45000,
    category: "Cháo/Mì",
    img: "https://cdn.tgdd.vn/Files/2020/05/20/1256925/cach-nau-chao-thit-bam-trung-bach-thao-bo-duong-cho-ca-nha-202206021404116484.jpg",
  },
  {
    id: 24,
    name: "Mì Hoành Thánh Tôm",
    description:
      "Sợi mì trứng tươi cùng hoành thánh nhân tôm thịt, nước dùng thanh.",
    price: 75000,
    category: "Cháo/Mì",
    img: "https://i.ytimg.com/vi/vS5BAn2_3Wc/maxresdefault.jpg",
  },
  {
    id: 25,
    name: "Bánh Bao Chỉ",
    description: "Bánh nếp dẻo nhân đậu xanh, dừa sợi hoặc mè đen.",
    price: 35000,
    category: "Tráng Miệng",
    img: "https://i.ytimg.com/vi/Uj58E97Yx68/maxresdefault.jpg",
  },
  {
    id: 26,
    name: "Bánh Củ Cải Chiên",
    description: "Bánh củ cải mềm bên trong, áp chảo vàng đều hai mặt.",
    price: 48000,
    category: "Món Chiên",
    img: "https://i.ytimg.com/vi/K5zE4_T1B1o/maxresdefault.jpg",
  },
  {
    id: 27,
    name: "Ham Sui Gok",
    description: "Bánh nếp chiên nhân thịt heo và nấm, vỏ giòn dẻo.",
    price: 50000,
    category: "Món Chiên",
    img: "https://i.ytimg.com/vi/W9zM1tIuB7s/maxresdefault.jpg",
  },
  {
    id: 28,
    name: "Rong Biển Cuộn Tôm Hấp",
    description: "Nhân tôm thịt cuộn trong lá rong biển, hấp cách thủy.",
    price: 65000,
    category: "Món Hấp",
    img: "https://i.ytimg.com/vi/f88p6YwY4pQ/maxresdefault.jpg",
  },
  {
    id: 29,
    name: "Đậu Hũ Tứ Xuyên",
    description: "Đậu hũ non mềm mịn nấu cùng sốt cay đặc trưng.",
    price: 80000,
    category: "Món Mặn",
    img: "https://i.ytimg.com/vi/W66X6m0S1yE/maxresdefault.jpg",
  },
  {
    id: 30,
    name: "Trà Phổ Nhĩ",
    description: "Loại trà đen truyền thống, giúp tiêu hóa tốt khi ăn Dimsum.",
    price: 25000,
    category: "Đồ Uống",
    img: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQ1RnbShNDrJxhWOYE3AivgyT2nCgeoko3iy7cS5cGsb6Wf8IszZqSBAHiBhasvekzLZLMjNOAqOQdgFb5D1Dp707YzaZ7S6oYRLNv1g9s3uqmXTg8gSdcXvbNAD6MsLFGGrMGIDP4&usqp=CAc",
  },
  {
    id: 31,
    name: "Trà Hoa Cúc",
    description: "Trà hoa cúc thanh nhiệt, ngọt dịu nhẹ nhàng.",
    price: 25000,
    category: "Đồ Uống",
    img: "https://down-vn.img.susercontent.com/file/vn-11134207-7ras8-m3rp3rcvn0gxa0.webp",
  },
  {
    id: 32,
    name: "Bánh Bao Trứng Muối Tan Chảy",
    description: "Vỏ bánh đen (tinh than tre) nhân kim sa óng ánh.",
    price: 55000,
    category: "Bánh Bao",
    img: "https://i.ytimg.com/vi/2X6S-n69Uj8/maxresdefault.jpg",
  },
  {
    id: 33,
    name: "Sủi Cảo Tứ Xuyên (Sốt Cay)",
    description: "Sủi cảo luộc rưới sốt sa tế cay nồng, mè rang thơm phức.",
    price: 60000,
    category: "Sủi Cảo",
    img: "https://i.ytimg.com/vi/mI6O6Gj0rM0/maxresdefault.jpg",
  },
  {
    id: 34,
    name: "Mì Xào Giòn Hải Sản",
    description: "Mì chiên giòn rưới sốt hải sản và rau củ thập cẩm.",
    price: 120000,
    category: "Cháo/Mì",
    img: "https://i.ytimg.com/vi/L6E4vXhVn58/maxresdefault.jpg",
  },
  {
    id: 35,
    name: "Dương Chi Cam Lộ",
    description: "Chè xoài bưởi cốt dừa, món tráng miệng nổi tiếng Hong Kong.",
    price: 45000,
    category: "Tráng Miệng",
    img: "https://i.ytimg.com/vi/2C_p-4WwR1I/maxresdefault.jpg",
  },
];
