export const dimsumProducts = [
  // --- 10 MÓN SỦI CẢO (ID 1 - 10) ---
  {
    id: 1,
    name: "Sủi Cảo Viên Mix từng loại ",
    description: "Vỏ mỏng, nhân thịt heo tươi ngon truyền thống.",
    price: 7000,
    category: "Sủi Cảo",
    img: "https://down-vn.img.susercontent.com/file/vn-11134207-820l4-mizr4q8lfif64c@resize_w900_nl.webp",
  },
  {
    id: 2,
    name: "Sủi Cảo Chiên Giòn",
    description: "Sủi cảo thịt chiên giòn rụm, ăn kèm giấm đen.",
    price: 58000,
    category: "Sủi Cảo",
    img: "https://down-vn.img.susercontent.com/file/sg-11134201-22100-umm5iz9fizivdc.webp",
  },
  {
    id: 3,
    name: "Sủi Cảo Tứ Xuyên (Sốt Cay)",
    description: "Sủi cảo luộc rưới sốt sa tế cay nồng đậm đà.",
    price: 60000,
    category: "Sủi Cảo",
    img: "https://hfood.com.vn/images/images/S%E1%BB%A7i_c%E1%BA%A3o_t%C3%B4m_th%E1%BB%8Bt_tr%E1%BB%99n_d%E1%BA%A7u_%E1%BB%9Bt_cay_ki%E1%BB%83u_T%E1%BB%A9_Xuy%C3%AAn_%C4%91%E1%BA%B7c_bi%E1%BB%87t.jpg",
  },
  {
    id: 4,
    name: "Sủi Cảo Tôm Gà",
    description: "Nhân ức gà thanh đạm kết hợp tôm tươi.",
    price: 62000,
    category: "Sủi Cảo",
    img: "https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?q=80&w=500",
  },
  {
    id: 5,
    name: "Sủi Cảo Nấm Hương",
    description: "Thịt heo băm trộn nấm hương rừng thơm nồng.",
    price: 55000,
    category: "Sủi Cảo",
    img: "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lm7ozzvknd2733@resize_w900_nl.webp",
  },
  {
    id: 6,
    name: "Sủi Cảo Bắp Mỹ",
    description: "Vị ngọt tự nhiên từ bắp hạt và thịt băm.",
    price: 55000,
    category: "Sủi Cảo",
    img: "https://down-vn.img.susercontent.com/file/ad0fa8cc9974c73990328783a1319a04.webp",
  },
  {
    id: 7,
    name: "Sủi Cảo Bào Ngư",
    description: "Nhân hải sản cao cấp với miếng bào ngư nhỏ.",
    price: 95000,
    category: "Sủi Cảo",
    img: "https://kenh14cdn.com/2020/8/30/4-1598772127011517482639.jpg",
  },
  {
    id: 8,
    name: "Sủi Cảo Tôm Hành Hẹ",
    description: "Vị hẹ tươi nồng nàn kết hợp thịt tôm và hành hẹ béo ngậy.",
    price: 52000,
    category: "Sủi Cảo",
    img: "https://down-vn.img.susercontent.com/file/vn-11134207-7ra0g-m785j9jjri0s53.webp",
  },
  {
    id: 9,
    name: "Sủi Cảo Chay Rau Củ",
    description: "Nhân nấm, cà rốt, đậu hũ cho người ăn chay.",
    price: 50000,
    category: "Sủi Cảo",
    img: "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lzo3l9wlhjd9ac.webp",
  },
  {
    id: 10,
    name: "Sủi Cảo Thịt Bằm",
    description: "Vỏ mỏng, nhân thịt heo tươi ngon truyền thống.",
    price: 55000,
    category: "Sủi Cảo",
    img: "https://images.unsplash.com/photo-1496116218417-1a781b1c416c?q=80&w=500",
  },

  // --- 10 MÓN HÁ CẢO (ID 11 - 20) ---
  {
    id: 11,
    name: "Há Cảo Viên từng loại",
    description: "Nhiều vị tha hồ lựa chọn.",
    price: 7500,
    category: "Há Cảo",
    img: "https://down-vn.img.susercontent.com/file/sg-11134201-22090-77c8b9j5wxhvfa@resize_w900_nl.webp",
  },

  {
    id: 12,
    name: "Há Cảo Hẹ",
    description: "Nhân tôm thịt hẹ, vỏ dai mềm đặc trưng.",
    price: 52000,
    category: "Há Cảo",
    img: "https://bizweb.dktcdn.net/100/448/704/products/ha-cao-he.png?v=1728119291670",
  },
  {
    id: 13,
    name: "Há Cảo Thủy Tinh",
    description: "Vỏ pha lê đẹp mắt, nhân tôm đỏ hồng.",
    price: 62000,
    category: "Há Cảo",
    img: "https://product.hstatic.net/200000299178/product/5_fc7c9024ca044bc1939ace90406015ef_1024x1024.jpg",
  },
  {
    id: 14,
    name: "Há Cảo Sò Điệp",
    description: "Cồi sò điệp tươi ngọt lịm bên trong.",
    price: 75000,
    category: "Há Cảo",
    img: "https://product.hstatic.net/200000299178/product/6_71d773826f3e461db150a820c9fe3bb4_1024x1024.jpg",
  },
  {
    id: 15,
    name: "Há Cảo Tôm Hấp",
    description: "Vỏ trong suốt, nhân tôm tươi nguyên con.",
    price: 60000,
    category: "Há Cảo",
    img: "https://images.unsplash.com/photo-1523905330026-b8bd1f5f320e?q=80&w=500",
  },

  {
    id: 16,
    name: "Há Cảo Măng Tây",
    description: "Nhân tôm tươi và măng tây giòn sần sật, thanh vị.",
    price: 62000,
    category: "Há Cảo",
    img: "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lzr17v030m1t20@resize_w900_nl.webp",
  },
  {
    id: 17,
    name: "Há Cảo Than Tre Tôm Thịt",
    description:
      "Vỏ tinh than tre đen tuyền, nhân hải sản độc lạ, sang trọng kết hợp với thịt tôm.",
    price: 68000,
    category: "Há Cảo",
    img: "https://down-vn.img.susercontent.com/file/sg-11134201-22110-u4g9t6oed9jv20@resize_w900_nl.webp",
  },
  {
    id: 18,
    name: "Há Cảo Thịt trứng muối",
    description: "Há cảo nhân trứng muối tan chảy béo ngậy, độc đáo.",
    price: 65000,
    category: "Há Cảo",
    img: "https://down-vn.img.susercontent.com/file/vn-11134201-7qukw-leuzd004tu1jae@resize_w900_nl.webp",
  },
  {
    id: 19,
    name: "Há Cảo Cá Hồi",
    description: "Sự kết hợp tinh tế giữa nhân cá hồi tươi và lớp vỏ mỏng mịn.",
    price: 85000,
    category: "Há Cảo",

    img: "https://down-vn.img.susercontent.com/file/vn-11134201-7qukw-leuz3kcjveyy7f@resize_w900_nl.webp",
  },
  {
    id: 20,
    name: "Vỉ Sủi Cảo, Há Cảo 300g, DimSum Há Cảo Tôm Thịt, Sủi Cảo Hải Sản, Thanh Cua, Sò Điệp, Chả Cá",
    description:
      "Há cảo vỏ áo ngoài màu trắng trong, thấy được nhân màu đặc trưng của thịt heo, cà rốt, gia vị... Sủi cảo màu vàng nhẹ - Vỏ bánh mỏng, mềm mịn dẻo dai với phần nhân từ thịt heo, thanh cua, sò điệp Nhật, chả cá...- Ăn kèm với nước chấm Dimsum.",
    price: 250000,
    category: "Há Cảo",
    img: "https://down-vn.img.susercontent.com/file/vn-11134207-7ra0g-m9e7fkcjwvgkfc@resize_w900_nl.webp",
  },

  // --- 10 MÓN XÍU MẠI (ID 21 - 30) ---
  {
    id: 21,
    name: "Xíu Mại Gạch Cua",
    description: "Nhân tôm thịt, phủ gạch cua vàng óng.",
    price: 50000,
    category: "Xíu Mại",
    img: "https://cdn.tgdd.vn/2022/05/CookDish/xiu-mai-la-gi-nguon-goc-va-cach-lam-xiu-mai-thom-ngon-don-avt-1200x676-1.jpg",
  },
  {
    id: 22,
    name: "Xíu mại sốt cà chay ",
    description: "Thịt băm bọc lòng đỏ trứng muối bùi béo.",
    price: 58000,
    category: "Xíu Mại",
    img: "https://down-vn.img.susercontent.com/file/vn-11134207-7ras8-m4o763j1q0av1f@resize_w900_nl.webp",
  },
  {
    id: 23,
    name: "Xiú mại bọc trứng cút",
    description: "Viên xíu mại to với tôm tươi sần sật.",
    price: 55000,
    category: "Xíu Mại",
    img: "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-ly6shh5wvf6p4d@resize_w900_nl.webp",
  },

  {
    id: 25,
    name: "Xíu mại da hoành thánh",
    description: "Thịt bò thăn mềm rưới sốt cay đậm đà.",
    price: 65000,
    category: "Xíu Mại",
    img: "https://down-vn.img.susercontent.com/file/vn-11134207-820l4-meqqsdtet81xb0@resize_w900_nl.webp",
  },
  {
    id: 26,
    name: "Xíu Mại Bamboo hàng cao cấp",
    description: "Cuộn lá rong biển bên ngoài nhân hải sản.",
    price: 58000,
    category: "Xíu Mại",
    img: "https://down-vn.img.susercontent.com/file/vn-11134207-820l4-mh5xz9a7mcjx6b@resize_w900_nl.webp",
  },
  {
    id: 27,
    name: "Xíu Mại Bò",
    description: "Nhân gà mềm quyện phô mai tan chảy.",
    price: 62000,
    category: "Xíu Mại",
    img: "https://down-vn.img.susercontent.com/file/b248d608b682fef3710b0cfc7f66cafb@resize_w900_nl.webp",
  },
  {
    id: 28,
    name: "Dimsum Mix Vị",
    description: "Hương vị thịt xá xíu đặc trưng trong viên xíu mại.",
    price: 55000,
    category: "Xíu Mại",
    img: "https://down-vn.img.susercontent.com/file/vn-11134207-820l4-meh4wekxzy138b@resize_w900_nl.webp",
  },
  {
    id: 29,
    name: "Xíu Mại Hồng Kông cuộn trứng muối",
    description: "Viên xíu mại bọc trong lá bó xôi xanh mướt.",
    price: 55000,
    category: "Xíu Mại",
    img: "https://down-vn.img.susercontent.com/file/vn-11134207-7ras8-mcp19h7mhdil9c@resize_w900_nl.webp",
  },
  {
    id: 30,
    name: "Xíu Mại Hoàng Kim",
    description: "Nhân hải sản phủ lớp bột vàng chiên nhẹ.",
    price: 70000,
    category: "Xíu Mại",
    img: "https://media.loveitopcdn.com/1551/212036-xiu-mai-hong-vuong.jpg",
  },
  {
    id: 24,
    name: "XÍU MẠI TÔM THỊT TRỨNG",
    description: "Nhân thịt trộn nấm đông cô băm nhỏ.",
    price: 52000,
    category: "Xíu Mại",
    img: "https://down-vn.img.susercontent.com/file/vn-11134258-81ztc-mm73mqnli60xb9",
  },

  // --- 10 MÓN NƯỚC (ID 31 - 40) ---
  {
    id: 31,
    name: "Trà Phổ Nhĩ",
    description: "Trà đen truyền thống, hỗ trợ tiêu hóa.",
    price: 25000,
    category: "Đồ Uống",
    img: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQ1RnbShNDrJxhWOYE3AivgyT2nCgeoko3iy7cS5cGsb6Wf8IszZqSBAHiBhasvekzLZLMjNOAqOQdgFb5D1Dp707YzaZ7S6oYRLNv1g9s3uqmXTg8gSdcXvbNAD6MsLFGGrMGIDP4&usqp=CAc",
  },
  {
    id: 32,
    name: "Trà Hoa Cúc",
    description: "Thanh nhiệt, ngọt dịu nhẹ nhàng.",
    price: 25000,
    category: "Đồ Uống",
    img: "https://down-vn.img.susercontent.com/file/vn-11134207-7ras8-m3rp3rcvn0gxa0.webp",
  },
  {
    id: 33,
    name: "Chè Dưỡng Nhan 12 vị",
    description: "Nấu từ nhãn nhục, táo đỏ, cực kỳ bổ dưỡng.",
    price: 30000,
    category: "Đồ Uống",
    img: "https://down-vn.img.susercontent.com/file/vn-11134207-7ras8-m5u5sje7ixhf6c@resize_w900_nl.webp",
  },
  {
    id: 34,
    name: "Trà dưỡng nhan 7 vị thảo mộc",
    description:
      "Trà Thảo Mộc dưỡng nhan giúp làm đẹp da, mát gan và thanh lọc cơ thể, mang đến giấc ngủ dễ dàng hơn",
    price: 20000,
    category: "Đồ Uống",
    img: "https://down-vn.img.susercontent.com/file/vn-11134207-7ras8-m2jdbatiowj618.webp",
  },
  {
    id: 35,
    name: "Trà Hoa atiso đỏ",
    description: "Vị trà đậm quyện chanh vàng thơm mát.",
    price: 35000,
    category: "Đồ Uống",
    img: "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lvhpxjuvnomc3c@resize_w900_nl.webp",
  },
  {
    id: 36,
    name: "TRÀ VẢI HẠT CHIA",
    description: "trà vải thơm mát ngon lịm.",
    price: 25000,
    category: "Đồ Uống",
    img: "https://down-vn.img.susercontent.com/file/e02283a4732bb4c42d3497bff2d97752@resize_w900_nl.webp",
  },

  // --- 5 MÓN TRÁNG MIỆNG (ID 41 - 45) ---
  {
    id: 41,
    name: "Pizza",
    description: "Pizza thơm ngon, nhân phô mai tan chảy.",
    price: 45000,
    category: "Tráng Miệng",
    img: "https://down-vn.img.susercontent.com/file/vn-11134207-7qukw-lf3lgvbxy2yya8@resize_w900_nl.webp",
  },
  {
    id: 42,
    name: "Bánh Tart Trứng",
    description: "Vỏ ngàn lớp giòn rụm, nhân trứng béo ngậy.",
    price: 48000,
    category: "Tráng Miệng",
    img: "https://down-vn.img.susercontent.com/file/vn-11134201-7ras8-mceaghrniibp88@resize_w900_nl.webp",
  },
  {
    id: 43,
    name: "Cao Quy Linh",
    description: "Thạch đen thanh mát giải nhiệt cực tốt.",
    price: 35000,
    category: "Tráng Miệng",
    img: "https://down-vn.img.susercontent.com/file/860a5b604fc1d210e7ed6a45f466ba76",
  },
  {
    id: 44,
    name: "Bánh mì hoa cúc",
    description: "Bánh mì nướng phô mai và rau củ.",
    price: 38000,
    category: "Tráng Miệng",
    img: "https://www.vitaminhouse.vn/cdn/shop/articles/banh-mi-hoa-cuc-phap-de-duoc-bao-lau-hap-dan_900x.jpg?v=1639059587",
  },
  {
    id: 45,
    name: "Bánh bông lan nho",
    description: "Bánh bông lan nho mềm xốp, vị ngọt nhẹ, thơm mùi nho khô.",
    price: 35000,
    category: "Tráng Miệng",
    img: "https://traicaynhapkhaububu.com/wp-content/uploads/2021/12/B%C3%81NH-B%C3%94NG-LAN-NHO-MADELEINES-PH%C3%81P-2.jpg",
  },

  // --- 3 MÓN BÁNH BAO (ID 46 - 48) ---
  {
    id: 46,
    name: "Bánh Bao Kim Sa",
    description: "Nhân trứng muối tan chảy óng ánh.",
    price: 45000,
    category: "Bánh Bao",
    img: "https://down-vn.img.susercontent.com/file/vn-11134207-7ra0g-m6vaeo9h995t1e.webp",
  },
  {
    id: 47,
    name: "Bánh Bao Xá Xíu",
    description: "Nhân xá xíu đậm đà, vỏ bánh xốp mềm.",
    price: 42000,
    category: "Bánh Bao",
    img: "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lsuve7ykhuis36.webp",
  },
  {
    id: 48,
    name: "Bánh Bao Than Tre",
    description: "Vỏ than tre, nhân sữa trứng đặc biệt.",
    price: 48000,
    category: "Bánh Bao",
    img: "https://down-vn.img.susercontent.com/file/vn-11134207-820l4-mjaz8jvs3aiv34.webp",
  },
];
